[build]
  base = "client"
  publish = "build"
  command = "CI= npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[context.production.environment]
  REACT_APP_API_URL = "https://entertainment-web-app-api.netlify.app"