[build]
  command = "CI=false npm run build"
  publish = "build"

[dev]
  command = "npm run start"
  port = 3000
  targetPort = 3000
  publish = "build"
  autoLaunch = true

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    # Add basic security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA configuration - always return index.html for all routes
[[redirects]]
  from = "/api/*"
  to = "https://emilia-burza-entertainment-app-server.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://emilia-burza-entertainment-app-server.netlify.app"
  REACT_APP_USE_FALLBACK = "true"

[context.development.environment]
  REACT_APP_API_URL = "http://localhost:3001"
  REACT_APP_USE_FALLBACK = "true"