[build]
  base = "server"
  publish = "dist"
  command = "npm install && npm run build"

[functions]
  directory = "dist/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[dev]
  port = 3001 